services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"

  worker:
    build:
      context: ./backend
    command: python worker.py
    volumes:
      - ./backend:/app
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis

  frontend:
    build:
      context: ./frontend
      #context: ./react-router-sample
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      #- ./react-router-sample:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development

  backend:
      build: ./backend
      ports:
        - "8000:8000"
      volumes:
        - ./backend:/app
      environment:
        - PYTHON_ENV=development
        - REDIS_URL=redis://redis:6379  # <-- use service name 'redis'
      depends_on:
        - redis

