version: "3.9"

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development

  backend:
      build: ./backend
      ports:
        - "8000:8000"
      volumes:
        - ./backend:/app
      environment:
        - PYTHON_ENV=development

